/*   Copyright (C) 2013-2014 Computer Sciences Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. */

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ezbake.query.intents;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ObjectState implements org.apache.thrift.TEnum {
  ACTIVE(0),
  AT_AIRFIELD(1),
  DECOMMISSIONED(2),
  DEPLOYED(3),
  FITTING_OUT(4),
  IN_FLIGHT(5),
  IN_GARRISON(6),
  IN_PORT(7),
  INACTIVE(8),
  OUT_OF_GARRISON(9),
  OUT_OF_PORT(10),
  UNDERWAY(11);

  private final int value;

  private ObjectState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ObjectState findByValue(int value) { 
    switch (value) {
      case 0:
        return ACTIVE;
      case 1:
        return AT_AIRFIELD;
      case 2:
        return DECOMMISSIONED;
      case 3:
        return DEPLOYED;
      case 4:
        return FITTING_OUT;
      case 5:
        return IN_FLIGHT;
      case 6:
        return IN_GARRISON;
      case 7:
        return IN_PORT;
      case 8:
        return INACTIVE;
      case 9:
        return OUT_OF_GARRISON;
      case 10:
        return OUT_OF_PORT;
      case 11:
        return UNDERWAY;
      default:
        return null;
    }
  }
}
