/*   Copyright (C) 2013-2014 Computer Sciences Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. */

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ezbake.query.intents;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Predicate extends org.apache.thrift.TUnion<Predicate, Predicate._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Predicate");
  private static final org.apache.thrift.protocol.TField BINARY_PREDICATE_FIELD_DESC = new org.apache.thrift.protocol.TField("binaryPredicate", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField UNARY_PREDICATE_FIELD_DESC = new org.apache.thrift.protocol.TField("unaryPredicate", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    BINARY_PREDICATE((short)1, "binaryPredicate"),
    UNARY_PREDICATE((short)2, "unaryPredicate");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BINARY_PREDICATE
          return BINARY_PREDICATE;
        case 2: // UNARY_PREDICATE
          return UNARY_PREDICATE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BINARY_PREDICATE, new org.apache.thrift.meta_data.FieldMetaData("binaryPredicate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, BinaryPredicate.class)));
    tmpMap.put(_Fields.UNARY_PREDICATE, new org.apache.thrift.meta_data.FieldMetaData("unaryPredicate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, UnaryPredicate.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Predicate.class, metaDataMap);
  }

  public Predicate() {
    super();
  }

  public Predicate(_Fields setField, Object value) {
    super(setField, value);
  }

  public Predicate(Predicate other) {
    super(other);
  }
  public Predicate deepCopy() {
    return new Predicate(this);
  }

  public static Predicate binaryPredicate(BinaryPredicate value) {
    Predicate x = new Predicate();
    x.setBinaryPredicate(value);
    return x;
  }

  public static Predicate unaryPredicate(UnaryPredicate value) {
    Predicate x = new Predicate();
    x.setUnaryPredicate(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, Object value) throws ClassCastException {
    switch (setField) {
      case BINARY_PREDICATE:
        if (value instanceof BinaryPredicate) {
          break;
        }
        throw new ClassCastException("Was expecting value of type BinaryPredicate for field 'binaryPredicate', but got " + value.getClass().getSimpleName());
      case UNARY_PREDICATE:
        if (value instanceof UnaryPredicate) {
          break;
        }
        throw new ClassCastException("Was expecting value of type UnaryPredicate for field 'unaryPredicate', but got " + value.getClass().getSimpleName());
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case BINARY_PREDICATE:
          if (field.type == BINARY_PREDICATE_FIELD_DESC.type) {
            BinaryPredicate binaryPredicate;
            binaryPredicate = new BinaryPredicate();
            binaryPredicate.read(iprot);
            return binaryPredicate;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case UNARY_PREDICATE:
          if (field.type == UNARY_PREDICATE_FIELD_DESC.type) {
            UnaryPredicate unaryPredicate;
            unaryPredicate = new UnaryPredicate();
            unaryPredicate.read(iprot);
            return unaryPredicate;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case BINARY_PREDICATE:
        BinaryPredicate binaryPredicate = (BinaryPredicate)value_;
        binaryPredicate.write(oprot);
        return;
      case UNARY_PREDICATE:
        UnaryPredicate unaryPredicate = (UnaryPredicate)value_;
        unaryPredicate.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case BINARY_PREDICATE:
          BinaryPredicate binaryPredicate;
          binaryPredicate = new BinaryPredicate();
          binaryPredicate.read(iprot);
          return binaryPredicate;
        case UNARY_PREDICATE:
          UnaryPredicate unaryPredicate;
          unaryPredicate = new UnaryPredicate();
          unaryPredicate.read(iprot);
          return unaryPredicate;
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case BINARY_PREDICATE:
        BinaryPredicate binaryPredicate = (BinaryPredicate)value_;
        binaryPredicate.write(oprot);
        return;
      case UNARY_PREDICATE:
        UnaryPredicate unaryPredicate = (UnaryPredicate)value_;
        unaryPredicate.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case BINARY_PREDICATE:
        return BINARY_PREDICATE_FIELD_DESC;
      case UNARY_PREDICATE:
        return UNARY_PREDICATE_FIELD_DESC;
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public BinaryPredicate getBinaryPredicate() {
    if (getSetField() == _Fields.BINARY_PREDICATE) {
      return (BinaryPredicate)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'binaryPredicate' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setBinaryPredicate(BinaryPredicate value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.BINARY_PREDICATE;
    value_ = value;
  }

  public UnaryPredicate getUnaryPredicate() {
    if (getSetField() == _Fields.UNARY_PREDICATE) {
      return (UnaryPredicate)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'unaryPredicate' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setUnaryPredicate(UnaryPredicate value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.UNARY_PREDICATE;
    value_ = value;
  }

  public boolean isSetBinaryPredicate() {
    return setField_ == _Fields.BINARY_PREDICATE;
  }


  public boolean isSetUnaryPredicate() {
    return setField_ == _Fields.UNARY_PREDICATE;
  }


  public boolean equals(Object other) {
    if (other instanceof Predicate) {
      return equals((Predicate)other);
    } else {
      return false;
    }
  }

  public boolean equals(Predicate other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(Predicate other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  /**
   * If you'd like this to perform more respectably, use the hashcode generator option.
   */
  @Override
  public int hashCode() {
    return 0;
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
