/*   Copyright (C) 2013-2014 Computer Sciences Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. */

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ezbake.query.intents;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class QueryAtom implements org.apache.thrift.TBase<QueryAtom, QueryAtom._Fields>, java.io.Serializable, Cloneable, Comparable<QueryAtom> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("QueryAtom");

  private static final org.apache.thrift.protocol.TField INTENT_FIELD_DESC = new org.apache.thrift.protocol.TField("intent", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField PREDICATES_FIELD_DESC = new org.apache.thrift.protocol.TField("predicates", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new QueryAtomStandardSchemeFactory());
    schemes.put(TupleScheme.class, new QueryAtomTupleSchemeFactory());
  }

  /**
   * 
   * @see ezbake.intents.IntentType
   */
  public ezbake.intents.IntentType intent; // required
  public List<Predicate> predicates; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see ezbake.intents.IntentType
     */
    INTENT((short)1, "intent"),
    PREDICATES((short)2, "predicates");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // INTENT
          return INTENT;
        case 2: // PREDICATES
          return PREDICATES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.INTENT, new org.apache.thrift.meta_data.FieldMetaData("intent", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, ezbake.intents.IntentType.class)));
    tmpMap.put(_Fields.PREDICATES, new org.apache.thrift.meta_data.FieldMetaData("predicates", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Predicate.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(QueryAtom.class, metaDataMap);
  }

  public QueryAtom() {
  }

  public QueryAtom(
    ezbake.intents.IntentType intent,
    List<Predicate> predicates)
  {
    this();
    this.intent = intent;
    this.predicates = predicates;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public QueryAtom(QueryAtom other) {
    if (other.isSetIntent()) {
      this.intent = other.intent;
    }
    if (other.isSetPredicates()) {
      List<Predicate> __this__predicates = new ArrayList<Predicate>(other.predicates.size());
      for (Predicate other_element : other.predicates) {
        __this__predicates.add(new Predicate(other_element));
      }
      this.predicates = __this__predicates;
    }
  }

  public QueryAtom deepCopy() {
    return new QueryAtom(this);
  }

  @Override
  public void clear() {
    this.intent = null;
    this.predicates = null;
  }

  /**
   * 
   * @see ezbake.intents.IntentType
   */
  public ezbake.intents.IntentType getIntent() {
    return this.intent;
  }

  /**
   * 
   * @see ezbake.intents.IntentType
   */
  public QueryAtom setIntent(ezbake.intents.IntentType intent) {
    this.intent = intent;
    return this;
  }

  public void unsetIntent() {
    this.intent = null;
  }

  /** Returns true if field intent is set (has been assigned a value) and false otherwise */
  public boolean isSetIntent() {
    return this.intent != null;
  }

  public void setIntentIsSet(boolean value) {
    if (!value) {
      this.intent = null;
    }
  }

  public int getPredicatesSize() {
    return (this.predicates == null) ? 0 : this.predicates.size();
  }

  public java.util.Iterator<Predicate> getPredicatesIterator() {
    return (this.predicates == null) ? null : this.predicates.iterator();
  }

  public void addToPredicates(Predicate elem) {
    if (this.predicates == null) {
      this.predicates = new ArrayList<Predicate>();
    }
    this.predicates.add(elem);
  }

  public List<Predicate> getPredicates() {
    return this.predicates;
  }

  public QueryAtom setPredicates(List<Predicate> predicates) {
    this.predicates = predicates;
    return this;
  }

  public void unsetPredicates() {
    this.predicates = null;
  }

  /** Returns true if field predicates is set (has been assigned a value) and false otherwise */
  public boolean isSetPredicates() {
    return this.predicates != null;
  }

  public void setPredicatesIsSet(boolean value) {
    if (!value) {
      this.predicates = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case INTENT:
      if (value == null) {
        unsetIntent();
      } else {
        setIntent((ezbake.intents.IntentType)value);
      }
      break;

    case PREDICATES:
      if (value == null) {
        unsetPredicates();
      } else {
        setPredicates((List<Predicate>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case INTENT:
      return getIntent();

    case PREDICATES:
      return getPredicates();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case INTENT:
      return isSetIntent();
    case PREDICATES:
      return isSetPredicates();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof QueryAtom)
      return this.equals((QueryAtom)that);
    return false;
  }

  public boolean equals(QueryAtom that) {
    if (that == null)
      return false;

    boolean this_present_intent = true && this.isSetIntent();
    boolean that_present_intent = true && that.isSetIntent();
    if (this_present_intent || that_present_intent) {
      if (!(this_present_intent && that_present_intent))
        return false;
      if (!this.intent.equals(that.intent))
        return false;
    }

    boolean this_present_predicates = true && this.isSetPredicates();
    boolean that_present_predicates = true && that.isSetPredicates();
    if (this_present_predicates || that_present_predicates) {
      if (!(this_present_predicates && that_present_predicates))
        return false;
      if (!this.predicates.equals(that.predicates))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(QueryAtom other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetIntent()).compareTo(other.isSetIntent());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIntent()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.intent, other.intent);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPredicates()).compareTo(other.isSetPredicates());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPredicates()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.predicates, other.predicates);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("QueryAtom(");
    boolean first = true;

    sb.append("intent:");
    if (this.intent == null) {
      sb.append("null");
    } else {
      sb.append(this.intent);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("predicates:");
    if (this.predicates == null) {
      sb.append("null");
    } else {
      sb.append(this.predicates);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (intent == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'intent' was not present! Struct: " + toString());
    }
    if (predicates == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'predicates' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class QueryAtomStandardSchemeFactory implements SchemeFactory {
    public QueryAtomStandardScheme getScheme() {
      return new QueryAtomStandardScheme();
    }
  }

  private static class QueryAtomStandardScheme extends StandardScheme<QueryAtom> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, QueryAtom struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // INTENT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.intent = ezbake.intents.IntentType.findByValue(iprot.readI32());
              struct.setIntentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PREDICATES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.predicates = new ArrayList<Predicate>(_list8.size);
                for (int _i9 = 0; _i9 < _list8.size; ++_i9)
                {
                  Predicate _elem10;
                  _elem10 = new Predicate();
                  _elem10.read(iprot);
                  struct.predicates.add(_elem10);
                }
                iprot.readListEnd();
              }
              struct.setPredicatesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, QueryAtom struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.intent != null) {
        oprot.writeFieldBegin(INTENT_FIELD_DESC);
        oprot.writeI32(struct.intent.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.predicates != null) {
        oprot.writeFieldBegin(PREDICATES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.predicates.size()));
          for (Predicate _iter11 : struct.predicates)
          {
            _iter11.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class QueryAtomTupleSchemeFactory implements SchemeFactory {
    public QueryAtomTupleScheme getScheme() {
      return new QueryAtomTupleScheme();
    }
  }

  private static class QueryAtomTupleScheme extends TupleScheme<QueryAtom> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, QueryAtom struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.intent.getValue());
      {
        oprot.writeI32(struct.predicates.size());
        for (Predicate _iter12 : struct.predicates)
        {
          _iter12.write(oprot);
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, QueryAtom struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.intent = ezbake.intents.IntentType.findByValue(iprot.readI32());
      struct.setIntentIsSet(true);
      {
        org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.predicates = new ArrayList<Predicate>(_list13.size);
        for (int _i14 = 0; _i14 < _list13.size; ++_i14)
        {
          Predicate _elem15;
          _elem15 = new Predicate();
          _elem15.read(iprot);
          struct.predicates.add(_elem15);
        }
      }
      struct.setPredicatesIsSet(true);
    }
  }

}

