/*   Copyright (C) 2013-2014 Computer Sciences Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. */

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.cloudera.impala.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TStatusCode implements org.apache.thrift.TEnum {
  OK(0),
  CANCELLED(1),
  ANALYSIS_ERROR(2),
  NOT_IMPLEMENTED_ERROR(3),
  RUNTIME_ERROR(4),
  MEM_LIMIT_EXCEEDED(5),
  INTERNAL_ERROR(6),
  RECOVERABLE_ERROR(7);

  private final int value;

  private TStatusCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TStatusCode findByValue(int value) { 
    switch (value) {
      case 0:
        return OK;
      case 1:
        return CANCELLED;
      case 2:
        return ANALYSIS_ERROR;
      case 3:
        return NOT_IMPLEMENTED_ERROR;
      case 4:
        return RUNTIME_ERROR;
      case 5:
        return MEM_LIMIT_EXCEEDED;
      case 6:
        return INTERNAL_ERROR;
      case 7:
        return RECOVERABLE_ERROR;
      default:
        return null;
    }
  }
}
